### ISSUE TITLE
wheels are not turning

### ISSUE THREAD

**Issue by lengagne** [agilexrobotics/limo_ros#1]
Hi, I have a limo robot.

I succeeded to make the robot running with the "normal" wheels.

I changed the wheel to the omnidirectionnal ones, but they are not running any more. 

When I published something in cmd_vel. I can hear a some noise (like something is locking), but the wheel still do not move. When I tried the ackermann, the direction is working.

Can you help me ?

**Comment by lengagne** [comment]
I saw that the omnidirectionnal mode can be change through the application (but I cannot install it on my phone). Is there a way to do it from the computer ?

**Comment by lengagne** [comment]
Eventually, I found one phone, I can change the mode. 
However, the wheels are still locked (small noise when tried to move)

**Comment by dashun1234** [comment]
It seems like the your setting and assembly were incorrect. The current mode on the LIMO should be in four-wheel differential mode on the body before you swap the wheels to omnidirectional ones. And it needs the small rollers on the omnidirectional wheels faced with vehicle center directly during your assembly. Here is the quick start guide for each mode setting and installation.  https://we.tl/t-Hp89VKudW1  . We will upload this manual to GitHub.  Take care about the installation direction. You can try it again @lengagne

**Comment by lengagne** [comment]
Hi, it seems I solved the issue. 

I unscrew the wheels and screw them with the little screws.
