### ISSUE TITLE
How do I control the eyes

### ISSUE THREAD

**Issue by engdorm** [agilexrobotics/limo_ros#2]
I want to change the "eyes" screen that just blink
I get that it's connected with serial 
but is there some driver for it?
is there some firmware that runs somewhere?
and if there is, can you supply an example

**Comment by dashun1234** [comment]
The “eyes” screen is controlled by the chassis's firmware. It's not opensource for users currently. So it's not supported to be changed by users. @engdorm

**Comment by engdorm** [comment]
ok 
thanks
