### ISSUE TITLE
lauch files description 

### ISSUE THREAD

**Issue by engdorm** [agilexrobotics/limo_ros#3]
Hi
in this video 
https://www.youtube.com/watch?v=icWWjyr9G_U
it looks like a map is been created 
and there is a localization node running

can you specify how you did it ?
which launch files should I use?
And do I need to first create the map with the cartographer or gmapping 
and then run other launches simultaneously? 
and if yes, which navigation (diff/ackerman/both)?

thanks

**Comment by dashun1234** [comment]
In section **6.2 Limo navigation function** in the user manual Limo，it has detail instruction about how to do it. You will need to replace the default map first with your new map before the navigation run. For more details ，you can get to this section in the user manual. @engdorm

**Comment by engdorm** [comment]
thanks for the quick response
where can I find this manual ?
all I got is one manual that explain how to switch the wheels and connect the app

**Comment by dashun1234** [comment]
@engdorm Here you are:    https://github.com/agilexrobotics/limo-doc
You will find more in our repositories in Github.
