### ISSUE TITLE
Run Gazebo simulation - are there ydlidar config details?

### ISSUE THREAD

**Issue by brianlmerritt** [agilexrobotics/limo_ros#5]
I am loading limo_ros into a catkin workspace, and catkin_make works fine but the launch gives an error

`Resource not found: ydlidar_ros
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/user/catkin_ws/src
ROS path [2]=/home/user/simulation_ws/src
ROS path [3]=/home/simulations/public_sim_ws/src`

When I add the ydlidar_ros repository I get a different error

`Error initializing YDLIDAR check Comms.
[ERROR] [1652111631.807010110]: Error initializing YDLIDAR Comms and Status!!!
[limo_base_node-2] process has died [pid 3318, exit code 255, cmd /home/user/catkin_ws/devel/lib/limo_base/limo_base_node__name:=limo_base_node __log:=/home/user/.ros/log/37b1dafa-cfb0-11ec-8b44-0242ac140007/limo_base_node-2.log]`

This doesn't seem like an error running on noetic instead of melodic.

Do I need to run a different branch of ydlidar_ros?  Or do I need to clone the version on the Limo (which doesn't appear to be from a public repository)?

Thanks if you can help!

**Comment by brianlmerritt** [comment]
I've just realised that although we have a description I need to launch a gazebo simulation package, not use the normal limo_ros launch which assumes the ydlidar is connected to live USB.  Any plans to create an agilex gazebo plugin with launch?  Or suggestions for another simulator that will work?  Many thanks!

**Comment by dashun1234** [comment]
Hi Brian,
Not sure for your requirement. But we have this separate Gazebo simulation demo for Limo. Hope it will help:https://github.com/agilexrobotics/ugv_gazebo_sim

**Comment by brianlmerritt** [comment]
Perfect - thanks!
